steps:
  # Build de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/portfolio-next'
      - '-f'
      - 'next/Dockerfile'
      - '--build-arg'
      - 'POUR_1=$$POUR_1'
      - '--build-arg'
      - 'POUR_2=$$POUR_2'
      - '--build-arg'
      - 'CONTRE_1=$$CONTRE_1'
      - '--build-arg'
      - 'CONTRE_2=$$CONTRE_2'
      - '--build-arg'
      - 'QWEN_1=$$QWEN_1'
      - '--build-arg'
      - 'QWEN_2=$$QWEN_2'
      - '--build-arg'
      - 'DEEPSEEK_1=$$DEEPSEEK_1'
      - '--build-arg'
      - 'DEEPSEEK_2=$$DEEPSEEK_2'
      - '--build-arg'
      - 'GEMINI_POUR_1=$$GEMINI_API_KEY_POUR_1'
      - '--build-arg'
      - 'GEMINI_POUR_2=$$GEMINI_API_KEY_POUR_2'
      - '--build-arg'
      - 'GEMINI_CONTRE_1=$$GEMINI_API_KEY_CONTRE_1'
      - '--build-arg'
      - 'GEMINI_CONTRE_2=$$GEMINI_API_KEY_CONTRE_2'
      - '--build-arg'
      - 'QWEN_API_1=$$QWEN_API_KEY_1'
      - '--build-arg'
      - 'QWEN_API_2=$$QWEN_API_KEY_2'
      - '--build-arg'
      - 'DEEPSEEK_API_1=$$DEEPSEEK_API_KEY_1'
      - '--build-arg'
      - 'DEEPSEEK_API_2=$$DEEPSEEK_API_KEY_2'
      - 'next'
    env:
      - 'POUR_1=$$POUR_1'
      - 'POUR_2=$$POUR_2'
      - 'CONTRE_1=$$CONTRE_1'
      - 'CONTRE_2=$$CONTRE_2'
      - 'QWEN_1=$$QWEN_1'
      - 'QWEN_2=$$QWEN_2'
      - 'DEEPSEEK_1=$$DEEPSEEK_1'
      - 'DEEPSEEK_2=$$DEEPSEEK_2'
      - 'GEMINI_API_KEY_POUR_1=$$GEMINI_API_KEY_POUR_1'
      - 'GEMINI_API_KEY_POUR_2=$$GEMINI_API_KEY_POUR_2'
      - 'GEMINI_API_KEY_CONTRE_1=$$GEMINI_API_KEY_CONTRE_1'
      - 'GEMINI_API_KEY_CONTRE_2=$$GEMINI_API_KEY_CONTRE_2'
      - 'QWEN_API_KEY_1=$$QWEN_API_KEY_1'
      - 'QWEN_API_KEY_2=$$QWEN_API_KEY_2'
      - 'DEEPSEEK_API_KEY_1=$$DEEPSEEK_API_KEY_1'
      - 'DEEPSEEK_API_KEY_2=$$DEEPSEEK_API_KEY_2'

  # Push de l'image vers Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio-next']

  # Déploiement sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'portfolio-next'
      - '--image'
      - 'gcr.io/$PROJECT_ID/portfolio-next'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'NEXT_PUBLIC_GEMINI_API_KEY_POUR_1=POUR_1:latest,NEXT_PUBLIC_GEMINI_API_KEY_POUR_2=POUR_2:latest,NEXT_PUBLIC_GEMINI_API_KEY_CONTRE_1=CONTRE_1:latest,NEXT_PUBLIC_GEMINI_API_KEY_CONTRE_2=CONTRE_2:latest,NEXT_PUBLIC_QWEN_API_KEY_1=QWEN_1:latest,NEXT_PUBLIC_QWEN_API_KEY_2=QWEN_2:latest,NEXT_PUBLIC_DEEPSEEK_API_KEY_1=DEEPSEEK_1:latest,NEXT_PUBLIC_DEEPSEEK_API_KEY_2=DEEPSEEK_2:latest,GEMINI_API_KEY_POUR=GEMINI_API_KEY_POUR_1:latest,GEMINI_API_KEY_CONTRE=GEMINI_API_KEY_CONTRE_1:latest,GEMINI_API_KEY=GEMINI_API_KEY_POUR_1:latest,GEMINI_API_KEY_SYNTHESE=GEMINI_API_KEY_POUR_1:latest,QWEN_API_KEY_1=QWEN_API_KEY_1:latest,QWEN_API_KEY_2=QWEN_API_KEY_2:latest,DEEPSEEK_API_KEY_1=DEEPSEEK_API_KEY_1:latest,DEEPSEEK_API_KEY_2=DEEPSEEK_API_KEY_2:latest'

images:
  - 'gcr.io/$PROJECT_ID/portfolio-next' 